language: rust
cache:
  directories:
    - $HOME/.cargo

    # Don't cache the target directory. It gets rather large, and the
    # unpacking of this ends up taking a rather long time!
    # - $TRAVIS_BUILD_DIR/target

rust:
  - 1.36.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
