[package]
name = "ddl-test"
version = "0.1.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
license = "Apache-2.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan = { git = "https://github.com/brendanzab/codespan" }
codespan-reporting = { git = "https://github.com/brendanzab/codespan" }
ddl-parse = { path = "../ddl-parse" }
ddl-compile-doc = { path = "../ddl-compile-doc" }
ddl-compile-rust = { path = "../ddl-compile-rust" }
lazy_static = "1.3"
