[package]
name = "ddl-edid"
version = "0.0.0"
license = "Apache-2.0"
publish = false

[dependencies]
ddl-util = { path = "../../../ddl-util" }

[build-dependencies]
ddl = { path = "../../.." }

[dev-dependencies]
hex = "0.3.1"
