[package]
name = "ddl-object_id"
version = "0.0.0"
license = "Apache-2.0"
publish = false

[dependencies]
ddl-util = { path = "../../../ddl-util" }
hex = "0.3.1"

[build-dependencies]
ddl = { path = "../../.." }
