[book]
title = "Fathom Book"
authors = ["YesLogic Pty. Ltd. <info@yeslogic.com>"]
description = "Documentation for the Fathom data description language"
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "build"

[output.html]
additional-js = [
    "dist/index.js",
]

[output.linkcheck]
follow-web-links = false # Avoid intermittent failures on CI from transient network errors
exclude = [
    '\./code-of-conduct\.md', # Bypass `traverse-parent-directories` for this symlink
]
