[book]
title = "DDL Book"
authors = ["Brendan Zabarauskas"]
description = "Documentation for the DDL"
multilingual = false
src = "src"

[build]
build-dir = "build"

[output.html]
mathjax-support = true
