name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  spec:
    runs-on: ubuntu-20.04
    name: Check Makam Specification
    steps:
      - uses: actions/checkout@v2
      - name: Install specification dependencies
        run: yarn install
        working-directory: ./experiments/makam-spec
      - name: Check specification
        run: yarn test
        working-directory: ./experiments/makam-spec

  check:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust: ["1.56.0", "stable", "beta", "nightly"]
    name: Check (${{ matrix.rust }})
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust: ["1.56.0", "stable", "beta", "nightly"]
    name: Test Suite (${{ matrix.rust }})
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust: ["stable"]
    name: Rustfmt (${{ matrix.rust }})
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal ${{ matrix.rust }} with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

#   clippy:
#     runs-on: ubuntu-20.04
#     strategy:
#       matrix:
#         rust: ["1.56.0", "stable", "beta", "nightly"]
#     name: Clippy (${{ matrix.rust }})
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install minimal ${{ matrix.rust }} with clippy
#         uses: actions-rs/toolchain@v1
#         with:
#           profile: minimal
#           toolchain: ${{ matrix.rust }}
#           override: true
#           components: clippy
#       - name: Run cargo clippy
#         uses: actions-rs/cargo@v1
#         with:
#           command: clippy
#           args: -- -D warnings
